//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.BanBiFlex.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANBIFLEX_RESERVA
    {
        public int ID { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> ID_ESPACIOTRABAJO { get; set; }
        public Nullable<int> ID_ESTACIONAMIENTO { get; set; }
        public string NROPLACA { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO_1 { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO_2 { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO_3 { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO_4 { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO_5 { get; set; }
        public string ESTADO { get; set; }
        public string HoraInicial { get; set; }
        public string HoraFinal { get; set; }
        public System.DateTime FECHARESERVA { get; set; }
        public string IP_PUERTA_INGRESO { get; set; }
    }
}
