//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.BanBiFlex.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class panelEntities : DbContext
    {
        public panelEntities()
            : base("name=panelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BANBIFLEX_RESERVA> BANBIFLEX_RESERVA { get; set; }
    
        public virtual ObjectResult<SP_BANBIFLEX_VALIDAR_FECHA_A_RESERVAR_Result1> SP_BANBIFLEX_VALIDAR_FECHA_A_RESERVAR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BANBIFLEX_VALIDAR_FECHA_A_RESERVAR_Result1>("SP_BANBIFLEX_VALIDAR_FECHA_A_RESERVAR");
        }
    
        public virtual int SP_BANBIFLEX_ACTUALIZA_ESTACIONAMIENTO_RESERVA(Nullable<int> iD, string fECHA, string tIPO)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var fECHAParameter = fECHA != null ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(string));
    
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BANBIFLEX_ACTUALIZA_ESTACIONAMIENTO_RESERVA", iDParameter, fECHAParameter, tIPOParameter);
        }
    
        public virtual ObjectResult<SP_BANBIFLEX_LISTAR_RESERVAS_Result> SP_BANBIFLEX_LISTAR_RESERVAS(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BANBIFLEX_LISTAR_RESERVAS_Result>("SP_BANBIFLEX_LISTAR_RESERVAS", iD_USUARIOParameter);
        }
    
        public virtual int SP_BANBIFLEX_ACTUALIZAR_ESTADO_RESERVA(Nullable<int> iD_RESERVA, string eSTADO)
        {
            var iD_RESERVAParameter = iD_RESERVA.HasValue ?
                new ObjectParameter("ID_RESERVA", iD_RESERVA) :
                new ObjectParameter("ID_RESERVA", typeof(int));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BANBIFLEX_ACTUALIZAR_ESTADO_RESERVA", iD_RESERVAParameter, eSTADOParameter);
        }
    
        public virtual ObjectResult<SP_BANBIFLEX_VALIDAR_SALAS_REUNIONES_Result> SP_BANBIFLEX_VALIDAR_SALAS_REUNIONES(string fECHA)
        {
            var fECHAParameter = fECHA != null ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BANBIFLEX_VALIDAR_SALAS_REUNIONES_Result>("SP_BANBIFLEX_VALIDAR_SALAS_REUNIONES", fECHAParameter);
        }
    
        public virtual ObjectResult<SP_BANBIFLEX_LOGIN_Result2> SP_BANBIFLEX_LOGIN(string dNI)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BANBIFLEX_LOGIN_Result2>("SP_BANBIFLEX_LOGIN", dNIParameter);
        }
    
        public virtual ObjectResult<string> SP_BANBIFLEX_VALIDAR_AFORO_PISO(Nullable<int> pISO, string fECHA)
        {
            var pISOParameter = pISO.HasValue ?
                new ObjectParameter("PISO", pISO) :
                new ObjectParameter("PISO", typeof(int));
    
            var fECHAParameter = fECHA != null ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_BANBIFLEX_VALIDAR_AFORO_PISO", pISOParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_BANBIFLEX_AFORO_SALA(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_BANBIFLEX_AFORO_SALA", iDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_BANBIFLEX_VALIDAR_CORREO_PARTICIPANTE(string cORREO)
        {
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_BANBIFLEX_VALIDAR_CORREO_PARTICIPANTE", cORREOParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_BANBIFLEX_VALIDAR_HORA_SALA(Nullable<int> iD, string hORA, string fECHA)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var hORAParameter = hORA != null ?
                new ObjectParameter("HORA", hORA) :
                new ObjectParameter("HORA", typeof(string));
    
            var fECHAParameter = fECHA != null ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_BANBIFLEX_VALIDAR_HORA_SALA", iDParameter, hORAParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SP_BANBIFLEX_VALIDAR_SITIO_USUARIO_Result2> SP_BANBIFLEX_VALIDAR_SITIO_USUARIO(Nullable<int> pISO, Nullable<int> nRO, string fECHA, Nullable<int> iDUSER)
        {
            var pISOParameter = pISO.HasValue ?
                new ObjectParameter("PISO", pISO) :
                new ObjectParameter("PISO", typeof(int));
    
            var nROParameter = nRO.HasValue ?
                new ObjectParameter("NRO", nRO) :
                new ObjectParameter("NRO", typeof(int));
    
            var fECHAParameter = fECHA != null ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(string));
    
            var iDUSERParameter = iDUSER.HasValue ?
                new ObjectParameter("IDUSER", iDUSER) :
                new ObjectParameter("IDUSER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BANBIFLEX_VALIDAR_SITIO_USUARIO_Result2>("SP_BANBIFLEX_VALIDAR_SITIO_USUARIO", pISOParameter, nROParameter, fECHAParameter, iDUSERParameter);
        }
    
        public virtual ObjectResult<SP_BANBIFLEX_LISTAR_RESERVAS_DOCUMENTO_Result> SP_BANBIFLEX_LISTAR_RESERVAS_DOCUMENTO(string dOCUMENTO, string hOSTNAME)
        {
            var dOCUMENTOParameter = dOCUMENTO != null ?
                new ObjectParameter("DOCUMENTO", dOCUMENTO) :
                new ObjectParameter("DOCUMENTO", typeof(string));
    
            var hOSTNAMEParameter = hOSTNAME != null ?
                new ObjectParameter("HOSTNAME", hOSTNAME) :
                new ObjectParameter("HOSTNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BANBIFLEX_LISTAR_RESERVAS_DOCUMENTO_Result>("SP_BANBIFLEX_LISTAR_RESERVAS_DOCUMENTO", dOCUMENTOParameter, hOSTNAMEParameter);
        }
    }
}
