//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.BanBiFlex.DA
{
    using System;
    
    public partial class SP_BANBIFLEX_LOGIN_Result1
    {
        public Nullable<int> ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> PISO { get; set; }
        public Nullable<int> NROSITIO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> DECLARACIONJURADA { get; set; }
        public Nullable<int> LISTANEGRA { get; set; }
        public Nullable<int> GRUPOCERO { get; set; }
    }
}
