//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.BanBiFlex.DA
{
    using System;
    
    public partial class SP_BANBIFLEX_VALIDAR_FECHA_A_RESERVAR_Result1
    {
        public string FECHINICIAL { get; set; }
        public string FECHAFINAL { get; set; }
    }
}
